@startuml
actor Bruker as Bruker
participant Frontend as Frontend
participant Backend as Backend
participant Generator as Generator
participant OpenAI_API as OpenAI_API

title Generering med verifisering som feiler

Bruker -> Frontend : Velger PaaS (App Service)
Frontend -> Backend : Forespør valgt PaaS
Backend -> Backend : Finner riktige inputfelter for PaaS
Backend -> Frontend : Sender riktige inputfelter
Frontend --> Bruker : Vist inputfeltene til bruker
Bruker -> Frontend : Bruker fyller ut inputfeltene
Frontend -> Backend : Sender inputdata
Backend -> Generator : Sender inputdata med instruksjoner

Generator -> OpenAI_API : Forespør generering av Terraform-kode
OpenAI_API --> Generator : Returnerer generert Terraform-kode


loop Opptil N forsøk
    Generator -> Generator : Kjører verifisering og validering
end loop

alt Verifisering feilet
    Generator --> Frontend : Verifisering feilet-melding
    Frontend --> Bruker : Viser "Verifisering feilet"-melding
end
@enduml