@startuml
title Scenario 2: Brukeren godtar verifisert Terraform-kode, men distribusjonen feiler

actor           Bruker          as  Bruker
participant     Frontend        as  Frontend
participant     Backend         as  Backend
participant     Generator       as  Generator
participant     OpenAI_API      as  OpenAI_API
participant     Azure           as  Azure
database        Database        as  Database

Bruker        ->      Frontend        :   Velger PaaS (App Service)
Frontend      ->      Backend         :   Forespør valgt PaaS
Backend       ->      Backend         :   Finner riktige inputfelter for PaaS
Backend       ->      Frontend        :   Sender riktige inputfelter
Frontend      -->     Bruker          :   Vist inputfeltene til bruker
Bruker        ->      Frontend        :   Bruker fyller ut inputfeltene
Frontend      ->      Backend         :   Sender innputtdata
Backend       ->      Generator       :   Sender inputdata med instruksjoner


Generator    ->      OpenAI_API             :   Forespør generering av Terraform-kode
OpenAI_API          -->     Generator       :   Returnerer generert Terraform-kode


loop Opptil N forsøk (brukerdefinert terskel)
    Generator   ->      Generator   :   Kører verifisering og validering
end loop


    Generator   ->      Backend     :   Sender fullstendig Terraform-kode
    Backend     -->     Frontend    :   Sender fullstendig Terraform-kode
    Frontend    -->     Bruker      :   Viser fullstendig Terraform-kode
    Bruker      ->      Frontend    :   Godkjenn kode


Frontend    ->      Backend         :   Bekrefter godkjenning av kode
Backend     ->      Database        :   Lagrer godkjent Terraform-kode
Bruker      ->      Frontend        :   Forespør distribusjon av Terraform-kode til Azure
Frontend    ->      Backend         :   Sender distribusjonsforespørsel
Backend     ->      Azure           :   Distribuerer Terraform-kode


Azure       ->      Backend         :   Distribusjon feilet
Backend     ->      Frontend        :   Sender feilmelding
Frontend    -->     Bruker          :   Viser feilmelding
@enduml