@startuml
title Scenario 2: Brukeren godtar verifisert Terraform-kode, men distribusjonen feiler

actor Bruker as Bruker
participant Frontend as Frontend
participant Backend as Backend
participant Generator as Generator
database Database as Database
participant Azure as Azure

Bruker        ->      Frontend        :   Velger PaaS (App Service)
Frontend      ->      Backend         :   Forespør valgt PaaS
Backend       ->      Backend         :   Finner riktige inputfelter
Backend       ->      Frontend        :   Sender inputfelter
Frontend      -->     Bruker          :   Viser inputfeltene
Bruker        ->      Frontend        :   Fyller ut inputfeltene
Frontend      ->      Backend         :   Sender inputdata
Backend       ->      Generator       :   Sender instruksjoner

Generator     ->      Database        :   Forespør moduler
Database      -->     Generator       :   Returnerer moduler
Generator     ->      Generator       :   Genererer og verifiserer Terraform-kode
Generator     -->     Backend         :   Sender komplett Terraform-kode

Backend       -->     Frontend        :   Returnerer Terraform-kode
Frontend      -->     Bruker          :   Viser Terraform-kode
Bruker        ->      Frontend        :   Godtar Terraform-kode

Frontend      ->      Backend         :   Bekrefter godkjenning
Backend       ->      Database        :   Lagrer godkjent Terraform-kode
Bruker        ->      Frontend        :   Forespør distribusjon
Frontend      ->      Backend         :   Sender distribusjonsforespørsel
Backend       ->      Azure           :   Distribuerer Terraform-kode

Azure         ->      Backend         :   Aviser distribusjon
Backend       ->      Frontend        :   Sender feilmelding
Frontend      -->     Bruker          :   Viser feilmelding og ber om ny handling

@enduml
