@startuml
'https://plantuml.com/sequence-diagram

title Sekvensdiagram for den manuelle genereringsprosessen i applikasjonen

' Aktører '
actor           Bruker          as Bruker
participant     Frontend        as Frontend
participant     Backend         as Backend
participant     Generator       as Generator
database        Database        as Database
participant     Azure           as Azure

Bruker        ->      Frontend        :   Velger PaaS (App Service)
Frontend      ->      Backend         :   Forespør valgt PaaS
Backend       ->      Backend         :   Finner riktige inputfelter for PaaS
Backend       ->      Frontend        :   Sender riktige inputfelter
Frontend      -->     Bruker          :   Vist inputfeltene til bruker
Bruker        ->      Frontend        :   Bruker fyller ut inputfeltene
Frontend      ->      Backend         :   Sender innputtdata
Backend       ->      Generator       :   Sender inputdata med instruksjoner

Generator     ->      Database        :   Forespør moduler
Database      -->     Generator       :   Returnerer moduler
Generator     ->      Generator       :   Genererer komplett IaC
Generator     ->      Generator       :   Verifiserer IaC
Generator     -->     Backend         :   Sender komplett IaC

Backend       -->     Frontend        :   Returnerer IaC
Frontend      -->     Bruker          :   Vist IaC
Bruker        ->      Frontend        :   Godtar/Avviser IaC

alt Bruker godtar IaC
    Frontend    ->      Backend         :   Bekrefter godkjenning av kode
    Backend     ->      Database        :   Lagrer godkjent IaC
    Bruker      ->      Frontend        :   Forespør distribusjon av IaC til Azure
    Frontend    ->      Backend         :   Sender distribusjonsforespørsel
    Backend     ->      Azure           :   Distribuerer IaC

    alt Distribusjon vellykket
        Azure       ->      Backend         :   Bekrefter distribusjon
        Backend     ->      Frontend        :   Bekrefter distribusjon
        Frontend    -->     Bruker          :   Viser suksessmelding
    else Distribusjon feilet
        Azure       ->      Backend         :   Feilmelding
        Backend     ->      Frontend        :   Sender feilmelding
        Frontend    -->     Bruker          :   Viser feilmelding og ber om ny handling
    end
else Bruker avviser IaC
    Bruker      ->      Frontend        :   Forespør ny generering
    Frontend    ->      Backend         :   Starter genereringsprosessen på nytt
end

@enduml
