@startuml
'https://plantuml.com/sequence-diagram

title Sequence Diagram for the Manual version of the Application

' Actors '
actor           User            as User
participant     Frontend        as Frontend
participant     Backend         as Backend
database        Database        as Database

User        ->      Frontend        :   Selects PaaS (App Service)
Frontend    ->      Backend         :   Requests modules
Backend     ->      Database        :   Requests modules
Database    -->     Backend         :   Returns modules
Backend     ->      Backend         :   Finds correct input tables for each module
Backend     -->     Frontend        :   Sends input tables
Frontend    -->     User            :   Shows user the input tables
User        ->      Frontend        :   User fills in the input tables
Frontend    ->      Backend         :   Sends filled input tables
Backend     ->      Backend         :   Generates complete terraform code
Backend     -->     Frontend        :   Returns complete terraform code
Frontend    -->     User            :   Returns complete terraform code

@enduml